In [1]:
import numpy as np

In [3]:
a = np.arange(15)

In [7]:
a = a.reshape(3,5)

In [8]:
a.shape

(3, 5)

In [9]:
a.dtype.name

'int64'

In [10]:
a.ndim

2

In [11]:
a.size

15

In [15]:
ls  = [[1,2,3,4],[5,6,7,8] ]

In [16]:
arr = np.array(ls)

In [17]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
a = np.zeros(100)

In [21]:
a.reshape(2,5,10)

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [22]:
a = np.ones(2)

In [23]:
a

array([ 1.,  1.])

In [24]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
e = np.empty(5)

In [27]:
e

array([ 0.,  0.,  0.,  0.,  0.])

In [ ]:
b += c 