In [1]:
import numpy as np

In [21]:
b = np.random.random((3,3))

In [22]:
c = np.random.random((3,3))

In [23]:
b

array([[ 0.03365253,  0.42778637,  0.93589176],
       [ 0.0610073 ,  0.25264715,  0.83763089],
       [ 0.42514159,  0.00318084,  0.33720532]])

In [15]:
b += c # b = b + c

In [16]:
b

array([[ 0.74910853,  0.81231262,  0.98551962],
       [ 0.14910248,  1.54632628,  1.65970953],
       [ 1.51290893,  0.90043006,  0.6574566 ]])

In [24]:
b ** 2

array([[  1.13249287e-03,   1.83001182e-01,   8.75893382e-01],
       [  3.72189125e-03,   6.38305802e-02,   7.01625507e-01],
       [  1.80745371e-01,   1.01177527e-05,   1.13707430e-01]])

In [25]:
0.03365253 * 0.03365253

0.0011324927754009