In [2]:
import numpy as np

In [2]:
ls = [12,334,45,56,78,89,4.5,34,9.09,34]

In [3]:
arr = np.array(ls)

In [8]:
arr.shape

(10,)

In [9]:
arr[2:5] # arr[a:b]

array([ 45.,  56.,  78.])

In [11]:
arr[3] 

33.0

In [12]:
arr[1:3] = 44

In [13]:
array_slice = arr[3:8]

In [14]:
array_slice

array([ 33. ,  78. ,  89. ,   4.5,  34. ])

In [18]:
array_slice[1:]

array([ 78. ,  89. ,   4.5,  34. ])

In [19]:
array_slice[:] = -1

In [20]:
array_slice

array([-1., -1., -1., -1., -1.])

In [21]:
arr

array([ 12.  ,  44.  ,  44.  ,  -1.  ,  -1.  ,  -1.  ,  -1.  ,  -1.  ,
         9.09,  34.  ])

In [22]:
arr2 = arr.copy()

In [23]:
arr2[3] = 55

In [24]:
arr2

array([ 12.  ,  44.  ,  44.  ,  55.  ,  -1.  ,  -1.  ,  -1.  ,  -1.  ,
         9.09,  34.  ])

In [3]:
arr = np.arange(90)

In [4]:
arr = arr.reshape(9,2,5)

In [50]:
arr[4][0][2]

42

In [48]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]]])

In [6]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84]],

       [[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89]]])