In [1]:
import numpy as np

In [3]:
arr1 = np.random.randn(12)

In [4]:
arr1

array([-1.06131635,  0.50613785, -0.26793653,  0.32603333,  1.05424548,
        0.70704122, -0.45628238, -1.40283785, -0.48578781,  0.52879476,
        0.15210847, -1.40138179])

In [6]:
np.exp(arr1)

array([ 0.34600005,  1.65887199,  0.76495633,  1.38546155,  2.86980901,
        2.02798202,  0.63363489,  0.24589815,  0.61521233,  1.69688593,
        1.16428652,  0.24625645])

In [7]:
arr2 = np.random.randn(12)

In [8]:
arr2

array([ 1.25327258, -0.32286677,  0.48844346, -0.98256273,  1.35157458,
        0.16177207,  1.16298203,  0.52023639,  0.22631509,  0.61760705,
       -0.77610883,  0.00318978])

In [9]:
np.add(arr1,arr2)

array([ 0.19195624,  0.18327108,  0.22050693, -0.65652939,  2.40582006,
        0.86881329,  0.70669965, -0.88260146, -0.25947272,  1.14640181,
       -0.62400036, -1.39819201])

In [ ]:
np.