In [1]:
import numpy as np

In [2]:
arr = np.random.randn(4,4)

In [3]:
arr

array([[ 0.72438829, -0.23604684,  0.08709038, -0.8878103 ],
       [-0.24715574, -1.15993826,  0.46149416,  1.93622653],
       [-3.39476972,  0.76991174, -1.21379138,  0.21347868],
       [ 0.61340278,  0.52064177, -0.47653289, -0.77117649]])

In [7]:
arr.var()

1.3290317015905895

In [9]:
np.where(arr < 0,0,arr)

array([[ 0.72438829,  0.        ,  0.08709038,  0.        ],
       [ 0.        ,  0.        ,  0.46149416,  1.93622653],
       [ 0.        ,  0.76991174,  0.        ,  0.21347868],
       [ 0.61340278,  0.52064177,  0.        ,  0.        ]])

In [10]:
arr.sort()

In [11]:
arr

array([[-0.8878103 , -0.23604684,  0.08709038,  0.72438829],
       [-1.15993826, -0.24715574,  0.46149416,  1.93622653],
       [-3.39476972, -1.21379138,  0.21347868,  0.76991174],
       [-0.77117649, -0.47653289,  0.52064177,  0.61340278]])